title: "The Desk Edit"
description: "Smart, affordable gear to upgrade your workspace"
email: workspace1180@gmail.com
timezone: UTC
baseurl: ""
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: the desk edit team
paginate: 30
disqus: 'demowebsite'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-113961478-1

# Authors
authors:
  You:
    name: the desk edit team
    display_name: the desk edit team
    avatar: 'assets/images/you.png'
    email: workspace1180@gmail.com
    web: https://selvorah.com
    twitter: https://twitter.com/
    description: "Founder of The Desk Edit. I test and round up affordable gear to make your workspace better."
  

# Social
social:
  instagram: https://www.instagram.com
  facebook: https://www.facebook.com
  twitter: https://twitter.com

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
